const mongoose = require("mongoose");
const Car = require("./car.model");
const Feed = require("./feed.model");
const NewCar = require("./newCar.model");
const Rent = require("./rent.model");
const User = require ("./user.model")
const db = {};
db.mongoose = mongoose;
db.car = Car;
db.feed = Feed
db.rent = Rent
db.user = User
db.newcar = NewCar
module.exports = db;
